version: '3.3'

services:

  wordpress:
    build:
      context: .
    depends_on:
      - db
    restart: on-failure
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      ANSPRESS_SITE_URL: localhost
      ANSPRESS_SITE_TITLE: "AnsPress demo site"
      ANSPRESS_DEFAULT_USER_EMAIL: admin@anspress.net
      ANSPRESS_DEFAULT_USER_PASSWORD: admin
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: